version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'chore'
      include: scope
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-minor', 'version-update:semver-patch']
    open-pull-requests-limit: 10
    target-branch: staging
