name: Feature Request
description: Suggest a new feature for the FlyByWire Discord bot
labels: [Request]
body:
  - type: markdown
    attributes:
      value: '# FBW Discord Bot Feature Request Form'
  - type: dropdown
    id: type
    attributes:
      label: Feature type
      description: What type of feature would this be?
      options:
        - Aircraft information
        - Support information
        - General information
        - Moderation feature
        - Utility or complex functionality
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: Description
      description: Describe the feature you'd like to see implemented. Is your feature request related to a problem?
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References (optional)
      description: If applicable, add screenshots or videos to help explain your request.
    validations:
      required: false
  - type: textarea
    id: misc
    attributes:
      label: Additional info (optional)
      description: Add any other context about the feature request here.
    validations:
      required: false
  - type: input
    id: discord
    attributes:
      label: Discord Username (optional)
      description: You may optionally provide your discord username, so that we may contact you directly about the issue.
      placeholder: ex. username#1234
    validations:
      required: false
