name: PR

on:
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
            - ready_for_review

jobs:
    lint:
        runs-on: ubuntu-latest
        if: github.event.pull_request.draft == false
        steps:
            - name: Checkout source
              uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Use Node.js 24.x
              uses: actions/setup-node@v4
              with:
                  node-version: '24.x'
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Check Lint
              run: pnpm run lint
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Use Node.js 24.x
              uses: actions/setup-node@v4
              with:
                  node-version: '24.x'
                  cache: 'pnpm'
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Build
              run: pnpm run build
